/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import {useFrame} from "@react-three/fiber";

const Cactus =(props) => {

    const ref = useRef()

    // Create a variable to track elapsed time
    let elapsedTime = 0

    useFrame((state, delta) => {
        if (ref.current) {
            // Increment elapsed time using delta (time between frames)
            elapsedTime += delta

            // Apply a sine wave for smooth breathing effect
            const amplitude = 0.1 // The range of movement
            const frequency = 0.5 // The speed of oscillation (Hz)
            ref.current.position.y = Math.sin(elapsedTime * frequency * Math.PI * 2) * amplitude
        }
    })




    const { nodes, materials } = useGLTF('/models/level-react-draco.glb')
    return (
        <mesh {...props}
              ref = {ref}
              castShadow
              receiveShadow
              name="Cube001_0"
              geometry={nodes.Cube001_0.geometry}
              material={materials['AstronautFallingTexture.png']}
              skeleton={nodes.Cube001_0.skeleton}

        />
    )
}

useGLTF.preload('models/level-react-draco.glb')

export default Cactus
